### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by finzaghi9** [CodeLunatic/anything-download#5]
![prtsc20200409180101](https://user-images.githubusercontent.com/197476/78883500-2bf97400-7a8c-11ea-9e9d-c317ab28fadc.png)
![prtsc20200409180127](https://user-images.githubusercontent.com/197476/78883505-2d2aa100-7a8c-11ea-84fb-088b96d3ca7e.png)

**Comment by CodeLunatic** [comment]
因为你没有打包`application-ui`，进入`application-ui`目录，然后执行`npm run build`

**Comment by CodeLunatic** [comment]
现在还处于草稿阶段，正在抽时间开发...
